name: dev_dependencies
description: "Common dev dependencies"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

dev_dependencies:
  lints: ^2.0.0

