name: domain
description: Domain module
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  core:
    path: ../core
  data:
    path: ../data

  get_it: any
  uuid: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
